### ISSUE TITLE
callback

### ISSUE THREAD

**Issue by logofakt** [alexantr/yii2-elfinder#1]
Where should I place callbacks?

**Comment by alexantr** [comment]
What callbacks you mean?

**Comment by logofakt** [comment]
In the public function actions within the controller, under options there is an option "bind" where you can define callback functions for specific actions like copy, delete, ... It looks like this:

> 
        return [
            'connector' => [
                'class' => ConnectorAction::className(),
                'options' => [
                    'locale' => 'de',
                    //'bind' => ['upload rm paste' => ['fileSync', 'sync']],
                    'roots' => [
                        [
I do not know where to put the class 'fileSync' and its action 'sync'. Is it a special directory to put the file fileSync.php with the class in or should I simly write ['fileController', 'sync'] and put an action into the FileController (you specified it as ElfinderController in your readme.md)? There is no complete example for this issue.
Thanks in advance for helping.

**Comment by alexantr** [comment]
Check [example](https://github.com/Studio-42/elFinder/wiki/Logging) from elFinder's wiki and look for "Using class instance callback".

You can create public method "sync" in your FileController and add to config `[$this, 'sync']`
