### ISSUE TITLE
Need changes in InputFile

### ISSUE THREAD

**Issue by sptik12** [alexantr/yii2-elfinder#12]
Thank you very much for elfinder in yii2, it's very useful.
Can you make a one minor change?
Can you give ability to pass in clientRoute for InputFIle widget not a a string only, but an array also. 
All what you need is change the following string:
   $route = [$this->clientRoute];
to 
   $route = is_array($this->clientRoute()) ? $this->clientRoute() : [$this->clientRoute]

I need to pass some data in clientRoute.
Currenly I should do something like Url::to(['/elfinder/courses', 'itemid' => 12]) to get an url as string.
In UrlManager suffix is enabled (it is set to .html), as a result I cannot get 'itemid' property in action.

If I have ability to pass clientRoute just as an array such as  ['/elfinder/courses', 'itemid' => 12]
problem will be solved.

Thanks

**Comment by alexantr** [comment]
Please check new release. Also now you can extend `InputFile` and change method `createRoute()` for more options.
