### ISSUE TITLE
Отлов событий

### ISSUE THREAD

**Issue by AlexeyGen** [alexantr/yii2-elfinder#4]
Можно ли отлавливать события на странице (например, событие выбора файла)?
И если можно, то как это сделать? Основная цель - менять миниатюру ( отображать миниатюру выбранного файла). Стандартные события поля input (change, input, etc) не срабатывают при программном изменении значения поля. Как прикрутить события самого elfinder'a - непонятно. Костыли городить постоянной проверкой значения через setInterval не хочется.
Уже второй день бьюсь, не могу справиться.

**Comment by alexantr** [comment]
Мое упущение. Забыл добавить вызов события "change" после выбора файла.

**Comment by AlexeyGen** [comment]
То есть нужно будет обновиться через composer, и вешать обработчик на событие "change"? 
Когда можно будет?

**Comment by alexantr** [comment]
Верно. Релиз уже создал.

**Comment by AlexeyGen** [comment]
Спасибо!
