### ISSUE TITLE
CSS: Search input

### ISSUE THREAD

**Issue by githubjeka** [alexantr/yii2-elfinder#5]
![image](https://user-images.githubusercontent.com/874234/27035275-6d6bff92-4f89-11e7-9986-bc7b8ad5fcaf.png)

**Comment by alexantr** [comment]
See README:

> *Note:* If you are using Bootstrap 3 enable `buttonNoConflict` option to resolve conflict between
Bootstrap and jQuery UI buttons.

**Comment by githubjeka** [comment]
I'm sorry to trouble you. Thanks.

**Comment by githubjeka** [comment]
> VM4164:2 Uncaught TypeError: jQuery.fn.button.noConflict is not a function

To fix this need add `JqueryAsset` to view file
```php
<?php
\yii\web\JqueryAsset::register($this);
?>
<?= alexantr\elfinder\ElFinder::widget([
    'connectorRoute' => ['dashboard/connector'],
    'settings' => [
        'height' => 640,
    ],
    'buttonNoConflict' => true,
]) ?>
```

I don't know is should be it is described in README or not, may be is specific case for me (I use pjax app)

**Comment by githubjeka** [comment]
UPD: \yii\web\JqueryAsset::register($this); doesn't worked correctly.
Correct way to fix is https://github.com/alexantr/yii2-elfinder/pull/6

**Comment by alexantr** [comment]
Can you check version from master branch? I think the problem in jquery-ui loading after bootstrap.

**Comment by githubjeka** [comment]
Success

**Comment by alexantr** [comment]
OK. Find new release with fix.
