### ISSUE TITLE
have problem with elfinder and tinymce

### ISSUE THREAD

**Issue by mamadza** [alexantr/yii2-elfinder#8]
Hi, I have problem with url of selected image in tiny mce .
el finder work correctly It's upload image in the correct folder and show in elfinder , after I am choosing picture and show the url in modal like this:
https://user-images.githubusercontent.com/12842935/36190072-4e77908e-116b-11e8-8ec4-23b5d8a72df2.png
the url is like this: ../../uploads/tinymce/2.jpg
when I am in module my structure is like this: app/admin/
two dot came back to correct url and show picture in admin module but when I want to show picture with text in front end the url is not correct how can I fix this?

**Comment by alexantr** [comment]
It's a tinyMce's problem. Try to set `convert_urls` to `false. https://www.tinymce.com/docs/configure/url-handling/#convert_urls

**Comment by mamadza** [comment]
thank you
