### ISSUE TITLE
problem yii2-elfinder with higher verion yii2 2.016

### ISSUE THREAD

**Issue by omidmm16** [alexantr/yii2-elfinder#9]
Hello Alex
are you OK .
Thank you first of all for your great work.
First , thank you for your great work .
Then I installed this yii2- elfinder , but after updating yii2 from yii2.0.14 to the higher version 2.016 , I have a problem. please guide me . Thank you .
![screenshot 86](https://user-images.githubusercontent.com/11288871/38164142-135591e0-3515-11e8-9ff7-05659ab48784.png)

**Comment by alexantr** [comment]
But last Yii release is 2.0.15.1. Are you using dev version? Try to delete vendor folder and run `composer update`.

**Comment by omidmm16** [comment]
I used dev version , than change to stable , and update my project, it  work
thanks for your answer
